### ISSUE TITLE
这是最终版本？

### ISSUE THREAD

**Issue by hello432369** [avantcontra/p5.we#2]
这是最终版本？
能玩数学公式就够玩的
挺好的

**Comment by avantcontra** [comment]
微信小游戏开发生态不太友好，大部分精力其实是替微信团队填坑。
第二个原因是小游戏的发布认证条件比小程序严格很多，不太适合个人开发者快速传播作品。
所以一直在观望中。

近期小游戏似乎有了个人版，认证条件放宽了一些。
另外小程序的webgl的支持力度也放宽了一些。

不算最终版本，但什么时候更新未定，感谢关注，欢迎PR😄
