### ISSUE TITLE
mouseX 在实机上失效，该怎么处理呢？

### ISSUE THREAD

**Issue by 976772537** [avantcontra/p5.we#3]
window在实机上加载不出来，但是模拟器上可以正常使用

**Comment by avantcontra** [comment]
真机上打开调试窗口，看一下有什么log

**Comment by 976772537** [comment]
没有报错的信息，但是打印mouseX,pmouseX 都显示NaN，打印window显示的Object{} 内部不包括mouseX这些。

**Comment by avantcontra** [comment]
新版还未测试，或者你用文中的旧版本试试，p5 0.7.3

**Comment by skybosi** [comment]
用wx.touchStart wx.touchMove wx.touchEnd  来替换 mouseX mouseY ，如果是真机，adpater 需要适配调整一下
